### ISSUE TITLE
Firefight Modules Factions

### ISSUE THREAD

**Issue by NeroTheHero111** [raven-security-forces/RSF-CFG#23]
Currently there is only OPFOR to fight against as far as ive seen. Is it possible to Add another Dropdownlist in which you list the Side, then depending on that input in the second Dropdown it shows all the available factions.

Furthermore some Feedback: I would like to be able to set a more specific number of enemies. Even on "Light" it still spawns a lot of Squads and for Training purposes a smaller squad won't be able to handle the amount of enemies.

**Comment by SpartanD39** [comment]
I'll see what I can do.

**Comment by SpartanD39** [comment]
Adjusted spawn rates. 
Adjusted displayed factions in UI. Works as follows:
BLUFOR sees OPFOR + INDEP
OPFOR sees BLUFOR + INDEP
INDEP sees BLUFOR + OPFOR

_The functions/modules do not change side relations, and the faction you pick will spawn as the side the faction belongs to. **Side relations need to be set in/during the mission. This module has nothing to do with them.**_

Further adjustments to the UI/selections will require significant rewrites, and should be entered as a project for tracking.

[Changes are in the current pull request](https://github.com/raven-security-forces/RSF-Configuration-Files/pull/24)
