### ISSUE TITLE
Muzzleslot for RFB

### ISSUE THREAD

**Issue by SpartanD39** [raven-security-forces/RSF-CFG#4]
Originally reported [here](https://github.com/SpartanD39/CaliberConvert/issues/2)
 
Original:
Currently, RFB does not Support Muzzle Attachments

I defined Linkproxy for the muzzleslot and none of the added attachments appeared when selected.

**Comment by SpartanD39** [comment]
It appears the base model for the RFB doesn't support muzzle attachments:
https://feedback.bistudio.com/T66036

Base config defines the muzzleslot for the gun in SDAR_Base_F as:
`class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class MuzzleSlot
			{
			};
			class CowsSlot
			{
			};
			class PointerSlot
			{
			};
		};`

Overriding with custom config and then trying to attach the item causes this error to spam in the rpt every time you try it:
`proxy object for given proxyName(\A3\data_f\proxies\weapon_slots\MUZZLE) couldn't found!`

Possible solution is here:
[Bohemia Forums](https://forums.bohemia.net/forums/topic/211236-fix-for-a3data_fproxiesweapon_slotsmuzzle-couldnt-found/)

But this will involve editing the SDAR model, which is binarized and possibly unreadable. 

It is more likely that the model simply doesn't have the necessary memory points for a muzzle slot, and if a way can be found around that, it might be doable.

**Comment by NeroTheHero111** [comment]
Again, Model simply lacks Proxies, nothing we can do.
