### ISSUE TITLE
MagazineProxies

### ISSUE THREAD

**Issue by SpartanD39** [raven-security-forces/RSF-CFG#5]
Originally reported [here](https://github.com/SpartanD39/CaliberConvert/issues/3)

Original report:

Older Vanilla Weapons do not support Magazine Proxies ( Unconfirmed)
KH-2002, RFB, MG5, Stoner 99, QBU-88.

Either additional configuration is required for these configs or it is not defined at all and the weapon model would require editing. which would suck

**Comment by NeroTheHero111** [comment]
The Weapon Models themselves lack the proxies, nothing we can do afaik
