### ISSUE TITLE
Fix Soldier Config for other weapons.

### ISSUE THREAD

**Issue by NeroTheHero111** [raven-security-forces/RSF-CFG#8]
Changed Magwells means the Vanilla units using them have no Ammo currently.

**Comment by SpartanD39** [comment]
https://github.com/raven-security-forces/RSF-Configuration-Files/pull/9

Fix for LDF and CSAT factions. Pacific CSAT does not seem to need adjustment.

**Comment by SpartanD39** [comment]
Further updated, new pull request made.

**Comment by NeroTheHero111** [comment]
[https://github.com/raven-security-forces/RSF-Configuration-Files/pull/15](url)

Fixed All Soldier Config and Backpack Config

**Comment by NeroTheHero111** [comment]
[https://github.com/raven-security-forces/RSF-Configuration-Files/pull/15](url)

Fixed All Soldier Config and Backpack Config
